### ISSUE TITLE
[JENKINS-35129] After upgrade of 1.650 to 2.6 - unable to configure jobs

### ISSUE THREAD

**Issue by timja-bot** [timja-org/jenkins-gh-issues-poc-11-04#3537]
<p><a href="http://10.101.6.243:8080/view/Misc/job/Node-Keep-Alive/configure" class="external-link" target="_blank" rel="nofollow noopener">http://10.101.6.243:8080/view/Misc/job/Node-Keep-Alive/configure</a></p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">May 25, 2016 10:05:38 AM hudson.ExpressionFactory2$JexlExpression evaluate
WARNING: Caught exception evaluating: d.helpFile in /view/Misc/job/Node-Keep-Alive/configure. Reason: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.apache.commons.jexl.util.PropertyExecutor.execute(PropertyExecutor.java:125)
at org.apache.commons.jexl.util.introspection.UberspectImpl$VelGetterImpl.invoke(UberspectImpl.java:314)

Caused by: java.lang.NoClassDefFoundError: hudson/tasks/Ant
at java.lang.<span class="code-object">Class</span>.getDeclaredMethods0(Native Method)
at java.lang.<span class="code-object">Class</span>.privateGetDeclaredMethods(<span class="code-object">Class</span>.java:2625)
at java.lang.<span class="code-object">Class</span>.getDeclaredMethods(<span class="code-object">Class</span>.java:1868)
at org.kohsuke.stapler.ClassDescriptor.findMethods(ClassDescriptor.java:148)
at org.kohsuke.stapler.ClassDescriptor.<init>(ClassDescriptor.java:84)
at org.kohsuke.stapler.MetaClass.buildDispatchers(MetaClass.java:106)
at org.kohsuke.stapler.MetaClass.<init>(MetaClass.java:94)
at org.kohsuke.stapler.WebApp.getMetaClass(WebApp.java:203)
at org.kohsuke.stapler.jelly.groovy.GroovyFacet.createRequestDispatcher(GroovyFacet.java:106)
at org.kohsuke.stapler.RequestImpl.getView(RequestImpl.java:257)
at org.kohsuke.stapler.RequestImpl.getView(RequestImpl.java:252)
at hudson.model.Descriptor.getHelpFile(Descriptor.java:742)
at hudson.model.Descriptor.getHelpFile(Descriptor.java:724)
at hudson.model.Descriptor.getHelpFile(Descriptor.java:713)
... 167 more
Caused by: java.lang.ClassNotFoundException: hudson.tasks.Ant
at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
... 181 more
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Alex Carr" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=alex_carr">alex_carr</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-35129" target="_blank">After upgrade of 1.650 to 2.6 - unable to configure jobs</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Cannot Reproduce
<li><b>resolved</b>: 2016-06-01T16:12:54+00:00
<li><b>imported</b>: 2025-11-05
</ul></i>
</details>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=alex_carr">alex_carr</a>:</i>
<p>Work around: A downgrade of the Ant Plugin from 1.3 to 1.2 followed by an upgrade back to 1.3 and the exception above no longer occurs.</p>

<p>Note: At this point I seem to be experiencing the issue reported in: <a href="https://issues.jenkins.io/browse/JENKINS-35122" title="Job configuration screen stuck on LOADING" class="issue-link" data-issue-key="JENKINS-35122"><del>JENKINS-35122</del></a> - Job configuration screen stuck on LOADING</p>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>:</i>
<p>It's not related to <a href="https://issues.jenkins.io/browse/JENKINS-35122" title="Job configuration screen stuck on LOADING" class="issue-link" data-issue-key="JENKINS-35122"><del>JENKINS-35122</del></a>. Could you please check if you have the Ant plugin installed? Maybe it has not been activated on 2.6 due to the whatever reason</p>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=alex_carr">alex_carr</a>:</i>
<p>Yes, the Ant plugin is installed and activated. The downgrade and then upgrade of the Ant plugin resolved that problem (e.g. I no longer get an exception).</p>

<p>The only reason I linked this issue to <a href="https://issues.jenkins.io/browse/JENKINS-35122" title="Job configuration screen stuck on LOADING" class="issue-link" data-issue-key="JENKINS-35122"><del>JENKINS-35122</del></a> is that it describes the problem that I am now dealing with.</p>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck">danielbeck</a>:</i>
<p>Weird. Corrupted zip file/full disk resulting in failed plugin install, something like that?</p>

<p>Difficult to determine after the fact.</p>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=alex_carr">alex_carr</a>:</i>
<p>Plenty of disk space. Possibly a corrupted download. All set, thanks.</p>

**Comment by timja-bot** [comment]
<i>[Originally related to: <a href="https://github.com/timja-org/jenkins-gh-issues-poc-11-04/issues?q=in%3Atitle%20JENKINS-35122">JENKINS-35122</a>]</i>
