### ISSUE TITLE
[JENKINS-61261] Ivy ClassNotFoundException when using Grab

### ISSUE THREAD

**Issue by timja-bot** [timja-org/jenkins-gh-issues-poc-11-04#5226]
<p>We are getting the below exception when we try to initialize and configure Jenkins plugins through post build Groovy Script under init.groovy.d. We understood this is the issue with classloader not able to find ivy in its path. However, this is working with 2.176.2 and started breaking from 2.176.3.</p>

<p> <br/>
 <br/>
@Grab('org.yaml:snakeyaml:1.17')<br/>
import java.util.logging.Logger<br/>
import org.codehaus.groovy.control.CompilerConfiguration<br/>
import org.yaml.snakeyaml.Yaml<br/>
....<br/>
 <br/>
 <br/>
java.lang.ClassNotFoundException: org.apache.ivy.core.settings.IvySettings at java.net.URLClassLoader.findClass(URLClassLoader.java:382) at java.lang.ClassLoader.loadClass(ClassLoader.java:424) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:565) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) Caused: java.lang.NoClassDefFoundError: org/apache/ivy/core/settings/IvySettings<br/>
 <br/>
 <br/>
 <br/>
We performed various work around to resolve this and none of them were successful<br/>
 <br/>
Job-DSL or Event Listener plugin cannot used since this is a config script which execute before Jenkins plugin installation/configuration. Similarly none of the pipeline utilities steps can be used at this point.<br/>
 <br/>
Cannot copy Ivy.jar to $Jenkins_Home/war/WEB_INF/lib due to the fact we run Jenkins as a docker container and war path will be only exposed after docker run which eventually invokes init.groovy.d script.<br/>
 <br/>
Tried adding the jar through classloader.<br/>
 <br/>
 </p>

---
<details><summary><i>Originally reported by <a title="Gowtham Subramanian" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=gowthamsig">gowthamsig</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-61261" target="_blank">Ivy ClassNotFoundException when using Grab</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Not A Defect
<li><b>resolved</b>: 2020-03-10T13:42:33+00:00
<li><b>imported</b>: 2025-11-05
</ul></i>
</details>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=gowthamsig">gowthamsig</a>:</i>
<p>Found the issue is related to downloaded plugins not present at the plugins path.</p>
