### ISSUE TITLE
[JENKINS-34648] Cannot create new items after upgrade to 2.1

### ISSUE THREAD

**Issue by timja-bot** [timja-org/jenkins-gh-issues-poc-11-04#3452]
<p>I just upgraded from version 1.558 to 2.1 and after restart I have some NoSuchMethodError errors.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.NoSuchMethodError: hudson.model.Messages.ExternalJob_DisplayName()Ljava/lang/<span class="code-object">String</span>;
	at hudson.model.ExternalJob$DescriptorImpl.getDisplayName(ExternalJob.java:132)
	at hudson.ExtensionComponent.compareTo(ExtensionComponent.java:97)
	at hudson.ExtensionComponent.compareTo(ExtensionComponent.java:42)
	at java.util.ComparableTimSort.binarySort(ComparableTimSort.java:258)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:203)
	at java.util.Arrays.sort(Arrays.java:1312)
	at java.util.Arrays.sort(Arrays.java:1506)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:141)
	at hudson.ExtensionList.sort(ExtensionList.java:369)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:289)
	at hudson.ExtensionList.getComponents(ExtensionList.java:167)
	at hudson.DescriptorExtensionList.load(DescriptorExtensionList.java:185)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
	at hudson.ExtensionList.iterator(ExtensionList.java:156)
	at hudson.ExtensionList.get(ExtensionList.java:147)
	at com.cloudbees.jenkins.GitHubPushTrigger$DescriptorImpl.get(GitHubPushTrigger.java:329)
	at org.jenkinsci.plugins.github.migration.Migrator.migrate(Migrator.java:40)
	at org.jenkinsci.plugins.github.GitHubPlugin.postInitialize(GitHubPlugin.java:39)
	at hudson.PluginManager$2$1$2.run(PluginManager.java:433)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$8.runTask(Jenkins.java:1011)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
</pre>
</div></div>

<p>When clicking on "New Item", the resulting page is blank and the same error appear in the logs. The rest of the application seems to be operational.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">WARNING: Error <span class="code-keyword">while</span> serving https:<span class="code-comment">//ci.obiba.org/view/All/itemCategories
</span>...
Caused by: java.lang.NoSuchMethodError: hudson.model.Messages.ExternalJob_DisplayName()Ljava/lang/<span class="code-object">String</span>;
	at hudson.model.ExternalJob$DescriptorImpl.getDisplayName(ExternalJob.java:132)
	at hudson.model.View.doItemCategories(View.java:1058)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:320)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:163)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
</pre>
</div></div>
<p>I do not know if it's relevant but I can see other errors in the logs: </p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Caused by: java.lang.NullPointerException
at hudson.plugins.analysis.core.HealthReportBuilder.computeHealth(HealthReportBuilder.java:47)
at hudson.plugins.analysis.core.AbstractResultAction.getBuildHealth(AbstractResultAction.java:87)
at hudson.model.Job.getBuildHealthReports(Job.java:1122)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Yannick Marcon" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ymarcon">ymarcon</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-34648" target="_blank">Cannot create new items after upgrade to 2.1</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2016-05-07T12:37:09+00:00
<li><b>imported</b>: 2025-11-05
</ul></i>
</details>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=recena">recena</a>:</i>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ymarcon" class="user-hover" rel="ymarcon">ymarcon</a> How are you using this plugin? There are no releases.</p>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=recena">recena</a>:</i>
<p>I've updated the component field. This feature is provided by core.</p>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck">danielbeck</a>:</i>
<p>Which version of the Monitor External Jobs plugin is this?</p>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck">danielbeck</a>:</i>
<p>Caused by <a href="https://github.com/jenkinsci/external-monitor-job-plugin/commit/4175bb5f4fefe0fd7ffa73e195bd65233f83bdf5" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/external-monitor-job-plugin/commit/4175bb5f4fefe0fd7ffa73e195bd65233f83bdf5</a> and resolved by upgrading the External Monitor Job Plugin to 1.4.</p>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck">danielbeck</a>:</i>
<p>Only 1.3 and earlier didn't have <a href="https://github.com/jenkinsci/external-monitor-job-plugin/commit/4175bb5f4fefe0fd7ffa73e195bd65233f83bdf5" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/external-monitor-job-plugin/commit/4175bb5f4fefe0fd7ffa73e195bd65233f83bdf5</a> </p>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=aheritier">aheritier</a>:</i>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck" class="user-hover" rel="danielbeck">danielbeck</a><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=recena" class="user-hover" rel="recena">recena</a> I identified the bug. It is different and affecting only the latest version of the plugin : <a href="https://issues.jenkins.io/browse/JENKINS-36875" title="Empty screen when creating new jobs" class="issue-link" data-issue-key="JENKINS-36875"><del>JENKINS-36875</del></a></p>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=recena">recena</a>:</i>
<p>A <a href="https://github.com/jenkinsci/external-monitor-job-plugin/pull/14" class="external-link" target="_blank" rel="nofollow noopener">fix</a> was pushed.</p>
