### ISSUE TITLE
[JENKINS-21664] Plugins with optional dependencies and compiled with Java6 cause Exception in loading

### ISSUE THREAD

**Issue by timja-bot** [timja-org/jenkins-gh-issues-poc-11-04#12245]
<p>Steps to produce the problem:</p>
<ol>
	<li>Install Copy Artifact</li>
	<li>Disable Maven plugin</li>
	<li>Restart Jenkins</li>
	<li>Fails to load Copy Artifact with: (full stacktrace is attached)
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">1) Error injecting constructor, java.lang.NoClassDefFoundError: hudson/maven/MavenBuild
  at hudson.plugins.copyartifact.CopyArtifact$DescriptorImpl.<init>(Unknown Source)
</pre>
</div></div></li>
</ol>

<p>I found followings:</p>
<ul>
	<li>This can be reproduced when I package Copy Artifact with jdk 1.6.</li>
	<li>This cannot be reproduced when I package Copy Artifact with jdk 1.7.</li>
</ul>

<p>It seems that something strange happens in Jenkins plugin loading system.<br/>
It may be a problem with guice 4.0 introduced in <a href="https://github.com/jenkinsci/jenkins/commit/aea10298fed376979e41f4482dd6f2a916f4b23f" class="external-link" target="_blank" rel="nofollow noopener">aea10298</a> (may be guice does not work with Java1.6).</p>

<p>What I will do are:</p>
<ul>
	<li>Create a minimum plugin to reproduce the problem.</li>
	<li>Test what happens if reverted aea10298.</li>
	<li>Test what happens if downgrade guice to guice 3.0 (fails to compile?)</li>
</ul>

---
<details><summary><i>Originally reported by <a title="ikedam" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ikedam">ikedam</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-21664" target="_blank">Plugins with optional dependencies and compiled with Java6 cause Exception in loading</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="ikedam" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ikedam">ikedam</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Not A Defect
<li><b>resolved</b>: 2014-02-10T14:08:54+00:00
<li><b>imported</b>: 2025-11-05
</ul></i>
</details>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ikedam">ikedam</a>:</i>
<p>when depending on maven-plugin...</p>
<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<th class='confluenceTh'>JDK Jenkins</th>
<th class='confluenceTh'>1.523    </th>
<th class='confluenceTh'>1.524    </th>
</tr>
<tr>
<th class='confluenceTh'>1.6</th>
<td class='confluenceTd'> </td>
<td class='confluenceTd'>reproduce </td>
</tr>
<tr>
<th class='confluenceTh'>1.7</th>
<td class='confluenceTd'> </td>
<td class='confluenceTd'> </td>
</tr>
</tbody></table>
</div>


<p>when depending on an original plugin...</p>
<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<th class='confluenceTh'>JDK Jenkins</th>
<th class='confluenceTh'>1.523    </th>
<th class='confluenceTh'>1.524    </th>
</tr>
<tr>
<th class='confluenceTh'>1.6</th>
<td class='confluenceTd'>reproduce </td>
<td class='confluenceTd'>reproduce </td>
</tr>
<tr>
<th class='confluenceTh'>1.7</th>
<td class='confluenceTd'> </td>
<td class='confluenceTd'> </td>
</tr>
</tbody></table>
</div>


<p>It seems nothing to do with guice...</p>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ikedam">ikedam</a>:</i>
<p>Hmm... that difference seems caused by <a href="https://github.com/jenkinsci/jenkins/commit/a6926e1c51c0650a48dec68cbe402248742dd55c" class="external-link" target="_blank" rel="nofollow noopener">a6926e1c51c0650a48dec68cbe402248742dd55c</a>.<br/>
Installed, but disabled plugins are registered to class loaders in Jenkins < 1.524.</p>
