### ISSUE TITLE
[JENKINS-19453] Slave launcher fails after NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins$MasterComputer

### ISSUE THREAD

**Issue by timja-bot** [timja-org/jenkins-gh-issues-poc-11-04#11821]
<p>I am able to start slave.jar via ssh or via jnlp.<br/>
The log of the connection shows that the node is correctly started.<br/>
In a project, I have 2 main parts:</p>
<ul class="alternate" type="square">
	<li>a svn checkout</li>
	<li>a shell command to start cmake + compilation.</li>
</ul>

<p>If I launch my build, it hangs. Then, I disabled the svn checkout and leave only the shell command with a "echo hello".<br/>
If I start the build, it hangs with the following error message:</p>

<blockquote>
<p>Started by user anonymous<br/>
<span class="error">&#91;EnvInject&#93;</span> - Loading node environment variables.<br/>
Building remotely on slave_linux_64 in workspace /home/crystal/jenkins/workspace/TESTLinux<br/>
FATAL: command execution failed<br/>
java.io.IOException: Remote call on slave_linux_64 failed<br/>
	at hudson.remoting.Channel.call(Channel.java:723)<br/>
	at hudson.Launcher$RemoteLauncher.launch(Launcher.java:862)<br/>
	at hudson.Launcher$ProcStarter.start(Launcher.java:353)<br/>
	at hudson.Launcher$ProcStarter.join(Launcher.java:360)<br/>
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:91)<br/>
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:60)<br/>
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:804)<br/>
	at hudson.model.Build$BuildExecution.build(Build.java:199)<br/>
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:586)<br/>
	at hudson.model.Run.execute(Run.java:1603)<br/>
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:247)<br/>
Caused by: java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins$MasterComputer<br/>
	at hudson.Launcher$LocalLauncher.<init>(Launcher.java:755)<br/>
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:991)<br/>
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:965)<br/>
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)<br/>
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)<br/>
	at hudson.remoting.Request$2.run(Request.java:326)<br/>
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)<br/>
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)<br/>
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)<br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/>
	at hudson.remoting.Engine$1$1.run(Engine.java:63)<br/>
	at java.lang.Thread.run(Thread.java:724)<br/>
Build step 'Execute shell' marked build as failure<br/>
Finished: FAILURE</p></blockquote>

<p>When I looked at the jenkins directory I configured on the slave, all the required jar are present, the workspace directory is present and the build directory is correctly created by the jenkins master. But nothing in this directory.</p>

---
<details><summary><i>Originally reported by <a title="yann collette" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ycollet">ycollet</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-19453" target="_blank">Slave launcher fails after NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins$MasterComputer</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Kohsuke Kawaguchi" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=kohsuke">kohsuke</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-03-11T01:57:56+00:00
<li><b>imported</b>: 2025-11-05
</ul></i>
</details>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>:</i>
<p>We experience this issue since the migration to 1.509.2. It is being reproduced in 1.509.3 as well.<br/>
Seems that Windows JNLP slaves periodically fail into the death loop</p>

<blockquote>
<p><span class="error">&#91;EnvInject&#93;</span> - Loading node environment variables.<br/>
Building remotely on XXX in workspace C:\....<br/>
FATAL: command execution failed<br/>
java.io.IOException: Remote call on ru20-custom-codecs-farm09 failed<br/>
	at hudson.remoting.Channel.call(Channel.java:681)<br/>
	at hudson.Launcher$RemoteLauncher.launch(Launcher.java:862)<br/>
	at hudson.Launcher$ProcStarter.start(Launcher.java:353)<br/>
	at hudson.Launcher$ProcStarter.join(Launcher.java:360)<br/>
	...<br/>
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:237)<br/>
Caused by: java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins$MasterComputer<br/>
	at hudson.Launcher$LocalLauncher.<init>(Launcher.java:755)<br/>
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:991)<br/>
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:965)<br/>
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)<br/>
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)<br/>
	at hudson.remoting.Request$2.run(Request.java:326)<br/>
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)<br/>
	at java.util.concurrent.FutureTask.run(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br/>
	at hudson.remoting.Engine$1$1.run(Engine.java:58)<br/>
	at java.lang.Thread.run(Unknown Source)<br/>
Build step 'Execute Windows batch command' marked build as failure<br/>
Finished: FAILURE</p></blockquote>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>:</i>
<p>I think I have reproduced this scenario in a unit test, though there are complications that I would need @kohsuke’s assistance with.</p>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=scm_issue_link">scm_issue_link</a>:</i>
<p>Code changed in jenkins<br/>
User: Jesse Glick<br/>
Path:<br/>
 src/main/java/hudson/remoting/RemoteClassLoader.java<br/>
 src/test/java/hudson/remoting/ClassRemotingTest.java<br/>
 src/test/java/hudson/remoting/TestLinkage.java<br/>
<a href="http://jenkins-ci.org/commit/remoting/5532ffe6c987278cb0acbb1e6cdce96075a0e52f" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/remoting/5532ffe6c987278cb0acbb1e6cdce96075a0e52f</a><br/>
Log:<br/>
  <a href="https://issues.jenkins.io/browse/JENKINS-19453" title="Slave launcher fails after NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins$MasterComputer" class="issue-link" data-issue-key="JENKINS-19453"><del>JENKINS-19453</del></a> Seem to have reproduced the problem in a unit test.</p>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=scm_issue_link">scm_issue_link</a>:</i>
<p>Code changed in jenkins<br/>
User: Kohsuke Kawaguchi<br/>
Path:<br/>
 src/main/java/hudson/remoting/RemoteClassLoader.java<br/>
 src/test/java/hudson/remoting/ClassRemotingTest.java<br/>
 src/test/java/hudson/remoting/DummyClassLoader.java<br/>
 src/test/java/hudson/remoting/TestLinkage.java<br/>
<a href="http://jenkins-ci.org/commit/remoting/4efb4e1dd5675a5d22993b09ebb65adab5baa9e0" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/remoting/4efb4e1dd5675a5d22993b09ebb65adab5baa9e0</a><br/>
Log:<br/>
  <a href="https://issues.jenkins.io/browse/JENKINS-19453" title="Slave launcher fails after NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins$MasterComputer" class="issue-link" data-issue-key="JENKINS-19453"><del>JENKINS-19453</del></a> Propose fix: mask interrupt while loading a class</p>

<p>I think the crux of the issue is that, in general, a failed class loading<br/>
will never get retried. It is certainly the case when another class loading has triggered a<br/>
recurisve class loading as in this test case.</p>

<p>In <a href="https://github.com/jenkinsci/remoting/pull/19" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/remoting/pull/19</a> Jesse proposed to fix<br/>
this by dropping the whole RemoteClassLoader. But this will not work<br/>
since the said RemoteClassLoader cloud have loaded other classes that<br/>
might be already running. Dropping a classloader will not drop these<br/>
classes, and we end up just creating another classloader that loads<br/>
incompatible classes. That is a disaster waiting to happen.</p>

<p>In this fix, we simply make findClass non-interruptible. That is, if a<br/>
blocking remote operation gets interrupted, we catch that and simply<br/>
retry and refuse to give up. We'll remember to set the interrupt flag<br/>
back on, however, so that the interrupt signal doesn't disappear.</p>

<p>The net effect is as if the delivery of the interrupt was bit late than<br/>
usual. The way I see it, this is the only way to fix this.</p>

<p>The nesting of control structures here is horrible, but I can't think of<br/>
any better way to write this.</p>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=scm_issue_link">scm_issue_link</a>:</i>
<p>Code changed in jenkins<br/>
User: Kohsuke Kawaguchi<br/>
Path:<br/>
 src/main/java/hudson/remoting/RemoteClassLoader.java<br/>
 src/test/java/hudson/remoting/ClassRemotingTest.java<br/>
 src/test/java/hudson/remoting/DummyClassLoader.java<br/>
 src/test/java/hudson/remoting/TestLinkage.java<br/>
<a href="http://jenkins-ci.org/commit/remoting/425301511aeb5a876b224cf4e572b74447e08ebc" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/remoting/425301511aeb5a876b224cf4e572b74447e08ebc</a><br/>
Log:<br/>
  <span class="error">&#91;FIXED JENKINS-19453&#93;</span> Propose fix: mask interrupt while loading a class</p>

<p>I think the crux of the issue is that, in general, a failed class loading<br/>
will never get retried. It is certainly the case when another class loading has triggered a<br/>
recurisve class loading as in this test case.</p>

<p>In <a href="https://github.com/jenkinsci/remoting/pull/19" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/remoting/pull/19</a> Jesse proposed to fix<br/>
this by dropping the whole RemoteClassLoader. But this will not work<br/>
since the said RemoteClassLoader cloud have loaded other classes that<br/>
might be already running. Dropping a classloader will not drop these<br/>
classes, and we end up just creating another classloader that loads<br/>
incompatible classes. That is a disaster waiting to happen.</p>

<p>In this fix, we simply make findClass non-interruptible. That is, if a<br/>
blocking remote operation gets interrupted, we catch that and simply<br/>
retry and refuse to give up. We'll remember to set the interrupt flag<br/>
back on, however, so that the interrupt signal doesn't disappear.</p>

<p>The net effect is as if the delivery of the interrupt was bit late than<br/>
usual. The way I see it, this is the only way to fix this.</p>

<p>The nesting of control structures here is horrible, but I can't think of<br/>
any better way to write this.</p>


<p>Compare: <a href="https://github.com/jenkinsci/remoting/compare/bfbc7d693a50...425301511aeb" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/remoting/compare/bfbc7d693a50...425301511aeb</a></p>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>:</i>
<p>Thanks for fix!<br/>
I've marked the issue as "lts-candidate".</p>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>:</i>
<p>Actually fixed just now in <a href="https://github.com/jenkinsci/jenkins/commit/4137c46182a0652d2eed2897a1e797bdc3f8c7f9" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/commit/4137c46182a0652d2eed2897a1e797bdc3f8c7f9</a> which did not record any issue IDs in its comment so it would not have been noticed by the JIRA link daemon.</p>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ycollette">ycollette</a>:</i>
<p>Tested with 1.542 and it works now for me.<br/>
Thanks a lot,</p>

<p>YC</p>

**Comment by timja-bot** [comment]
<i><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=scm_issue_link">scm_issue_link</a>:</i>
<p>Code changed in jenkins<br/>
User: Oliver Gondža<br/>
Path:<br/>
<a href="http://jenkins-ci.org/commit/jenkins/5cf3e28c4885a86a4dad3463952e1aae34932f9c" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/jenkins/5cf3e28c4885a86a4dad3463952e1aae34932f9c</a><br/>
Log:<br/>
  <span class="error">&#91;FIXED JENKINS-20093 JENKINS-19453 JENKINS-19004 JENKINS-8856&#93;</span> Noting retroactively</p>

<p>Backported as 23424ea7dbced486963a73d6bf56e8367ab779dd</p>


<p>Compare: <a href="https://github.com/jenkinsci/jenkins/compare/7d602d52b445...5cf3e28c4885" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/compare/7d602d52b445...5cf3e28c4885</a></p>
